<?php

use Illuminate\Database\Seeder;

class BendaharaSeeder extends Seeder
{
    /**
     * 
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \App\Pejabat::insert([
            [ 
                "idunitkerja"=>42,
            	"nama"=> 'dr Anna Ujihandayani',
                "nip"=>'197610232006042009'	,
                "jabatan"=>'Bendahara Pengeluaran',
                "rekening"=>'1711001707',
                "alamat"=>'Jl. Asem Raya 8, Kec. Asemrowo',
                "idc"=>1,
                "idm"=>1,
            ],
            [ 
                "idunitkerja"=>148,
            	"nama"=> 'Dian Mahastuti R.A.K.W',
                "nip"=>'198605092015052001'	,
                "jabatan"=>'Bendahara Pengeluaran',
                "rekening"=>'1021004495',
                "alamat"=>'Jl. Raya Balas Klumprik, Kec. Wiyung',
                "idc"=>1,
                "idm"=>1,
            ],
            [ 
                "idunitkerja"=>41,
            	"nama"=> 'Tiyas Pranadani',
                "nip"=>'197603302005012010'	,
                "jabatan"=>'Bendahara Pengeluaran',
                "rekening"=>'1851002169',
                "alamat"=>'Jl. Balongsari Tama No.1, Kec. Tandes',
                "idc"=>1,
                "idm"=>1,
            ],
            [ 
                "idunitkerja"=>103,
            	"nama"=> 'Armaya Dewi Puspita, Amd Keb',
                "nip"=>'198611192017042002'	,
                "jabatan"=>'Bendahara Pengeluaran',
                "rekening"=>'1851002142',
                "alamat"=>'Jl. Raya Bangkingan RT.02 RW.II, Kec. Lakarsantri',
                "idc"=>1,
                "idm"=>1,
            ],
            [ 
                "idunitkerja"=>79,
            	"nama"=> 'Yunan Arie Dani, Amd.Kep',
                "nip"=>'198703162010011004'	,
                "jabatan"=>'Bendahara Pengeluaran',
                "rekening"=>'0011295479',
                "alamat"=>'Jl. Banyu Urip Kidul VI No. 8',
                "idc"=>1,
                "idm"=>1,
            ],
            [ 
                "idunitkerja"=>44,
            	"nama"=> 'Dini Savitri, Amd, An.Med',
                "nip"=>'197810212005012006'	,
                "jabatan"=>'Bendahara Pengeluaran',
                "rekening"=>'1851050481',
                "alamat"=>'Raya Benowo No. 47',
                "idc"=>1,
                "idm"=>1,
            ],
            [ 
                "idunitkerja"=>122,
            	"nama"=> 'Wiwin Wahyuningsih, A.Md.Keb',
                "nip"=>'197006081991022001'	,
                "jabatan"=>'Bendahara Pengeluaran',
                "rekening"=>'0761005201',
                "alamat"=>'Jalan Dukuh Lebar, Gg Perintis Utama',
                "idc"=>1,
                "idm"=>1,
            ],
            [ 
                "idunitkerja"=>51,
            	"nama"=> 'dr. Indah Hayati',
                "nip"=>'197303252002122001'	,
                "jabatan"=>'Bendahara Pengeluaran',
                "rekening"=>'0011295428',
                "alamat"=>'Jl. Pandegiling No.223, DR. Soetomo, Tegalsari,',
                "idc"=>1,
                "idm"=>1,
            ],
            [ 
                "idunitkerja"=>85,
            	"nama"=> 'drg. Nur Kamala',
                "nip"=>'196712092002122001'	,
                "jabatan"=>'Bendahara Pengeluaran',
                "rekening"=>'0381118703',
                "alamat"=>'Jl. Dukuh Kupang XXV No. 48',
                "idc"=>1,
                "idm"=>1,
            ],
            [ 
                "idunitkerja"=>61,
            	"nama"=> 'dr. Paramitha Kusuma Wardhani',
                "nip"=>'198602132014022001'	,
                "jabatan"=>'Bendahara Pengeluaran',
                "rekening"=>'0011295487',
                "alamat"=>'Gg. PoliklinikJl. Dupak Bangunrejo No. 6',
                "idc"=>1,
                "idm"=>1,
            ],
            [ 
                "idunitkerja"=>67,
            	"nama"=> 'Maria Magdalena B.SST',
                "nip"=>'196502061987032016'	,
                "jabatan"=>'Bendahara Pengeluaran',
                "rekening"=>'0761005227',
                "alamat"=>'Kapas Lor I F, Gading, Kec Tambaksari',
                "idc"=>1,
                "idm"=>1,
            ],
            [ 
                "idunitkerja"=>87,
            	"nama"=> 'Tri luki Suryasari,  A.Md. Kep',
                "nip"=>'198204062006042028'	,
                "jabatan"=>'Bendahara Pengeluaran',
                "rekening"=>'0011295339',
                "alamat"=>'Jl. Gayungsari Barat No. 124',
                "idc"=>1,
                "idm"=>1,
            ],
            [ 
                "idunitkerja"=>53,
            	"nama"=> 'Choirotun Indrawati, Amd Kesgi',
                "nip"=>'197606252006042021'	,
                "jabatan"=>'Bendahara Pengeluaran',
                "rekening"=>'1711001731',
                "alamat"=>'Jl. Margodadi No. 36-38',
                "idc"=>1,
                "idm"=>1,
            ],
            [ 
                "idunitkerja"=>73,
            	"nama"=> 'Anis Silviah, A.Md.Keb',
                "nip"=>'198502212017042007'	,
                "jabatan"=>'Bendahara Pengeluaran',
                "rekening"=>'1281001295',
                "alamat"=>'Jl. Gunung Anyar Lor No. 70',
                "idc"=>1,
                "idm"=>1,
            ],
            [ 
                "idunitkerja"=>81,
            	"nama"=> 'Rohmatin,S.Kep.,Ns',
                "nip"=>'198209272009022007'	,
                "jabatan"=>'Bendahara Pengeluaran',
                "rekening"=>'1281001287',
                "alamat"=>'Jl. Bendul Merisi No. 1, Jagir, Kec. Wonokromo',
                "idc"=>1,
                "idm"=>1,
            ],
            [ 
                "idunitkerja"=>88,
            	"nama"=> 'Reni Hidayah, A.Md Keb',
                "nip"=>'198108272006042037'	,
                "jabatan"=>'Bendahara Pengeluaran',
                "rekening"=>'1281001279',
                "alamat"=>'Jl. Jemursari Sel. IV No. 5, Jemur wonosari, Kec. Wonocolo',
                "idc"=>1,
                "idm"=>1,
            ],
            [ 
                "idunitkerja"=>45,
            	"nama"=> 'Sri Sulistiyowati',
                "nip"=>'196806241989012001'	,
                "jabatan"=>'Bendahara Pengeluaran',
                "rekening"=>'1851002100',
                "alamat"=>'Jl. Raya Menganti No. 277A, Jeruk, Kec. Lakarsantri ',
                "idc"=>1,
                "idm"=>1,
            ],
            [ 
                "idunitkerja"=>138,
            	"nama"=> 'Ni Ketut Apriani',
                "nip"=>'196704011989032011'	,
                "jabatan"=>'Bendahara Pengeluaran',
                "rekening"=>'0761005197',
                "alamat"=>'Jl. Kalijudan, Kalijudan, Kec. Mulyorejo',
                "idc"=>1,
                "idm"=>1,
            ],
            [ 
                "idunitkerja"=>70,
            	"nama"=> 'Indah Yuni A, Amd.Kesling',
                "nip"=>'198006282006042029'	,
                "jabatan"=>'Bendahara Pengeluaran',
                "rekening"=>'1281001368',
                "alamat"=>'Rungkut Puskesmas No.1, Kali Rungkut, Kec. Rungkut',
                "idc"=>1,
                "idm"=>1,
            ],
            [ 
                "idunitkerja"=>90,
            	"nama"=> 'drg. Indiati Sumedi M.Kes',
                "nip"=>'197811122006042018'	,
                "jabatan"=>'Bendahara Pengeluaran',
                "rekening"=>'1271005225',
                "alamat"=>'Kebonsari, Kec. Jambangan',
                "idc"=>1,
                "idm"=>1,
            ],
            [ 
                "idunitkerja"=>50,
            	"nama"=> 'HL. Yuly Ritasari, AMd.Kep',
                "nip"=>'197508082006042026'	,
                "jabatan"=>'Bendahara Pengeluaran',
                "rekening"=>'0011295347',
                "alamat"=>'Jl. Kaliasin Pompa No.79-81, Kedungdoro, Kec. Tegalsari',
                "idc"=>1,
                "idm"=>1,
            ],
            [ 
                "idunitkerja"=>84,
            	"nama"=> 'drg. Fatma Nur',
                "nip"=>'197701302009022001'	,
                "jabatan"=>'Bendahara Pengeluaran',
                "rekening"=>'1021004479',
                "alamat"=>'Jalan Raya No.46, Kedurus, Kec. Karang Pilang',
                "idc"=>1,
                "idm"=>1,
            ],
            [ 
                "idunitkerja"=>62,
            	"nama"=> 'Dian Puspa Sari',
                "nip"=>'198703252017042004'	,
                "jabatan"=>'Bendahara Pengeluaran',
                "rekening"=>'0011295533',
                "alamat"=>'Jalan Tambak Deres No.2, Kenjeran, Kec. Bulak',
                "idc"=>1,
                "idm"=>1,
            ],
            [ 
                "idunitkerja"=>135,
            	"nama"=> 'drg. Hanny Maharwati',
                "nip"=>'198004142010012004'	,
                "jabatan"=>'Bendahara Pengeluaran',
                "rekening"=>'0581006608',
                "alamat"=>'No 19 Sukolilo,Jl. Keputih Tegal, Keputih, Surabaya Timur',
                "idc"=>1,
                "idm"=>1,
            ],
            [ 
                "idunitkerja"=>49,
            	"nama"=> 'Tulistiani, Amd Kep',
                "nip"=>'197606082007012011'	,
                "jabatan"=>'Bendahara Pengeluaran',
                "rekening"=>'0011295321',
                "alamat"=>'Jl. Jaksa Agung Suprapto No.10, Ketabang, Kec. Genteng',
                "idc"=>1,
                "idm"=>1,
            ],
            [ 
                "idunitkerja"=>75,
            	"nama"=> 'Mus Adah, S.Kep., Ns',
                "nip"=>'197708302007012014'	,
                "jabatan"=>'Bendahara Pengeluaran',
                "rekening"=>'0581006594',
                "alamat"=>'Jl. Arief Rahman Hakim No.99 B, Klampis Ngasem, Kec. Sukolilo',
                "idc"=>1,
                "idm"=>1,
            ],
            [ 
                "idunitkerja"=>60,
            	"nama"=> 'dr. Heni May Yunanti',
                "nip"=>'198405022014022001'	,
                "jabatan"=>'Bendahara Pengeluaran',
                "rekening"=>'0011295398',
                "alamat"=>'Jl. Pesapen Selatan No.70, Krembangan Sel., Kec. Krembangan',
                "idc"=>1,
                "idm"=>1,
            ],
            [ 
                "idunitkerja"=>46,
            	"nama"=> 'dr.Kristien',
                "nip"=>'198211152010012017'	,
                "jabatan"=>'Bendahara Pengeluaran',
                "rekening"=>'1851002126',
                "alamat"=>'Jl. Menganti Lidah Kulon No.5, Lidah Kulon, Kec. Lakarsantri',
                "idc"=>1,
                "idm"=>1,
            ],
            [ 
                "idunitkerja"=>47,
            	"nama"=> 'Alfiyah',
                "nip"=>'198012292007012004'	,
                "jabatan"=>'Bendahara Pengeluaran',
                "rekening"=>'1851002118',
                "alamat"=>'Jl. Raya Lontar No.26, Lontar, Kec. Sambikerep',
                "idc"=>1,
                "idm"=>1,
            ],
            [ 
                "idunitkerja"=>104,
            	"nama"=> 'M. Husni Thamrin,Amd. Kep',
                "nip"=>'198106232026041024'	,
                "jabatan"=>'Bendahara Pengeluaran',
                "rekening"=>'1851002151',
                "alamat"=>'Jl. Raya Made No.116, Made, Kec. Sambikerep',
                "idc"=>1,
                "idm"=>1,
            ],
            [ 
                "idunitkerja"=>40,
            	"nama"=> 'Dyah Kristiningrum, Amd Kep',
                "nip"=>'197610032007012010'	,
                "jabatan"=>'Bendahara Pengeluaran',
                "rekening"=>'1851002134',
                "alamat"=>'Jl. Manukan Dalam I/18, Kec. Tandes',
                "idc"=>1,
                "idm"=>1,
            ],
            [ 
                "idunitkerja"=>71,
            	"nama"=> 'Savitri Ayuningtias',
                "nip"=>'198505022011012010'	,
                "jabatan"=>'Bendahara Pengeluaran',
                "rekening"=>'0011295525',
                "alamat"=>'Jl. Medokan Asri Utara IV/31, Kec. Rungkut',
                "idc"=>1,
                "idm"=>1,
            ],
            [ 
                "idunitkerja"=>74,
            	"nama"=> 'Mujiastutik, Amd Keb',
                "nip"=>'197212131993012003'	,
                "jabatan"=>'Bendahara Pengeluaran',
                "rekening"=>'0741005841',
                "alamat"=>'Jl. Manyar Rejo I/35, Kec. Sukolilo',
                "idc"=>1,
                "idm"=>1,
            ],
            [ 
                "idunitkerja"=>69,
            	"nama"=> 'drg. Terisna Erijanti',
                "nip"=>'197605062006041020'	,
                "jabatan"=>'Bendahara Pengeluaran',
                "rekening"=>'0011295312',
                "alamat"=>'Jl. Mojo Klanggru Wetan II/11, Kec. Gubeng',
                "idc"=>1,
                "idm"=>1,
            ],
            [ 
                "idunitkerja"=>117,
            	"nama"=> 'dr.Diah Roichan Arifiani.,M.Kes',
                "nip"=>'197408132007012011'	,
                "jabatan"=>'Bendahara Pengeluaran',
                "rekening"=>'0011295495',
                "alamat"=>'Jl. Tambak Asri XIII/17, Kec. Krembangan',
                "idc"=>1,
                "idm"=>1,
            ],
            [ 
                "idunitkerja"=>76,
            	"nama"=> 'dr. Ranti Ana Ningsih',
                "nip"=>'198507172011012014'	,
                "jabatan"=>'Bendahara Pengeluaran',
                "rekening"=>'0011295282',
                "alamat"=>'Jl. Mulyorejo Utara 201 Blk, Kec. Mulyorejo',
                "idc"=>1,
                "idm"=>1,
            ],
            [ 
                "idunitkerja"=>83,
            	"nama"=> 'dr. Ferra Setiawati',
                "nip"=>'197712022005012010'	,
                "jabatan"=>'Bendahara Pengeluaran',
                "rekening"=>'1281001325',
                "alamat"=>'Jl. Ngagel Dadi III/17, Kec. Wonokromo',
                "idc"=>1,
                "idm"=>1,
            ],
            [ 
                "idunitkerja"=>66,
            	"nama"=> 'Dewi Mu\'alifah',
                "nip"=>'198001012005012017'	,
                "jabatan"=>'Bendahara Pengeluaran',
                "rekening"=>'0761005219',
                "alamat"=>'Jl. Jolotundo Baru III/16, Kec. Tambaksari',
                "idc"=>1,
                "idm"=>1,
            ],
            [ 
                "idunitkerja"=>80,
            	"nama"=> 'Indri Yuliana, Amd Keb',
                "nip"=>'198303222014022001'	,
                "jabatan"=>'Bendahara Pengeluaran',
                "rekening"=>'0011295894',
                "alamat"=>'Jl. Makam Kembang Kuning No.6, Kec. Sawahan',
                "idc"=>1,
                "idm"=>1,
            ],
            [ 
                "idunitkerja"=>57,
            	"nama"=> 'Diyah Widianingsih',
                "nip"=>'197305231998032011'	,
                "jabatan"=>'Bendahara Pengeluaran',
                "rekening"=>'0011295541',
                "alamat"=>'Jl. Karang Tembok 39, Kec. Semampir',
                "idc"=>1,
                "idm"=>1,
            ],
            [ 
                "idunitkerja"=>48,
            	"nama"=> 'Tintin Masyiah, A.Md kesgi',
                "nip"=>'196608291987032007'	,
                "jabatan"=>'Bendahara Pengeluaran',
                "rekening"=>'0011295363',
                "alamat"=>'Jl. Makam Peneleh 35, Kec. Genteng',
                "idc"=>1,
                "idm"=>1,
            ],
            [ 
                "idunitkerja"=>56,
            	"nama"=> 'Vicha Mayasari, A.Md.Keb',
                "nip"=>'198612162009022008'	,
                "jabatan"=>'Bendahara Pengeluaran',
                "rekening"=>'0011295355',
                "alamat"=>'Jl. Jakarta No.9, Kec. Pabean Cantian',
                "idc"=>1,
                "idm"=>1,
            ],
            [ 
                "idunitkerja"=>68,
            	"nama"=> 'drg.Ummi Latifah',
                "nip"=>'198105182016012001'	,
                "jabatan"=>'Bendahara Pengeluaran',
                "rekening"=>'0011197272',
                "alamat"=>'Jl. Pucang Anom Timur 72 Surabaya',
                "idc"=>1,
                "idm"=>1,
            ],
            [ 
                "idunitkerja"=>78,
            	"nama"=> 'drg Ines Puspawardhani',
                "nip"=>'197208222005012008'	,
                "jabatan"=>'Bendahara Pengeluaran',
                "rekening"=>'0381118690',
                "alamat"=>'Jl. Kupang Gunung Raya No. 5 Surabaya',
                "idc"=>1,
                "idm"=>1,
            ],
            [ 
                "idunitkerja"=>65,
            	"nama"=> 'Anung Mega Retno',
                "nip"=>'197901062007012005'	,
                "jabatan"=>'Bendahara Pengeluaran',
                "rekening"=>'0011295517',
                "alamat"=>'Jl. Rangkah VII/94, Kec. Tambaksari',
                "idc"=>1,
                "idm"=>1,
            ],
            [ 
                "idunitkerja"=>77,
            	"nama"=> 'drg. Farida Rahayu Sulistyowati',
                "nip"=>'197404082006042029'	,
                "jabatan"=>'Bendahara Pengeluaran',
                "rekening"=>'0011295371',
                "alamat"=>'Jl. Raya Arjuna 119, Kec. Sawahan',
                "idc"=>1,
                "idm"=>1,
            ],
            [ 
                "idunitkerja"=>984,
            	"nama"=> 'Citra Riayani, A.Md Keb',
                "nip"=>'198207202008012010'	,
                "jabatan"=>'Bendahara Pengeluaran',
                "rekening"=>'1881001868',
                "alamat"=>'Jl. Sawah Pulo Lapangan No. 2',
                "idc"=>1,
                "idm"=>1,
            ],
            [ 
                "idunitkerja"=>43,
            	"nama"=> 'drg.Betanti Mulyantini',
                "nip"=>'197512072005012007'	,
                "jabatan"=>'Bendahara Pengeluaran',
                "rekening"=>'1851050490',
                "alamat"=>'Jl. Raya Kendung, Kec. Benowo',
                "idc"=>1,
                "idm"=>1,
            ],
            [ 
                "idunitkerja"=>89,
            	"nama"=> 'Trina Dyah Murniati, Amd Keb',
                "nip"=>'198109262017042002'	,
                "jabatan"=>'Bendahara Pengeluaran',
                "rekening"=>'1281001317',
                "alamat"=>'Jl. Sidosermo Gg. Damri No. 51, Kec. Wonocolo',
                "idc"=>1,
                "idm"=>1,
            ],
            [ 
                "idunitkerja"=>58,
            	"nama"=> 'drg. Esti Wuryaningtyas',
                "nip"=>'197712192006042020'	,
                "jabatan"=>'Bendahara Pengeluaran',
                "rekening"=>'0011295304',
                "alamat"=>'Jl. Sidodadi II',
                "idc"=>1,
                "idm"=>1,
            ],
            [ 
                "idunitkerja"=>64,
            	"nama"=> 'Ni Putu Adi Nirmala P',
                "nip"=>'199005302014022001'	,
                "jabatan"=>'Bendahara Pengeluaran',
                "rekening"=>'0761005235',
                "alamat"=>'Jl. Randu 102, Kec. Kenjeran',
                "idc"=>1,
                "idm"=>1,
            ],
            [ 
                "idunitkerja"=>55,
            	"nama"=> 'dr. Nihayah Rohmatul Laili',
                "nip"=>'198205282011012009'	,
                "jabatan"=>'Bendahara Pengeluaran',
                "rekening"=>'0011295380',
                "alamat"=>'Jl. Simolawang II Barat No. 45 A, Kec. Simokerto',
                "idc"=>1,
                "idm"=>1,
            ],
            [ 
                "idunitkerja"=>39,
            	"nama"=> 'dr. Ratna Trianasari',
                "nip"=>'198205202011012017'	,
                "jabatan"=>'Bendahara Pengeluaran',
                "rekening"=>'1711001723',
                "alamat"=>'Jl. Gumuk Bogo VI/1, Kec. Sukomanunggal',
                "idc"=>1,
                "idm"=>1,
            ],
            [ 
                "idunitkerja"=>151,
            	"nama"=> 'drg. Ernin Sumiratwati',
                "nip"=>'197404292002122005'	,
                "jabatan"=>'Bendahara Pengeluaran',
                "rekening"=>'1281001350',
                "alamat"=>'Jl. Siwalankerto No. 134, Kec. Wonocolo',
                "idc"=>1,
                "idm"=>1,
            ],
            [ 
                "idunitkerja"=>121,
            	"nama"=> 'Wahyu Umaroh, Amd Kep',
                "nip"=>'197804172014122004'	,
                "jabatan"=>'Bendahara Pengeluaran',
                "rekening"=>'0011295401',
                "alamat"=>'Jl. Tambak Wedi, Kec. Kenjeran',
                "idc"=>1,
                "idm"=>1,
            ],
            [ 
                "idunitkerja"=>54,
            	"nama"=> 'Junawangsih',
                "nip"=>'197901032005012013'	,
                "jabatan"=>'Bendahara Pengeluaran',
                "rekening"=>'0951004685',
                "alamat"=>'Jl. Ngaglik 87, Kec. Simokerto',
                "idc"=>1,
                "idm"=>1,
            ],
            [ 
                "idunitkerja"=>63,
            	"nama"=> 'Dina Indah Pratiwi Amd Keb',
                "nip"=>'199012122014022001'	,
                "jabatan"=>'Bendahara Pengeluaran',
                "rekening"=>'0011295509',
                "alamat"=>'Jl. Kedung Cowek 226, Kec. Kenjeran ',
                "idc"=>1,
                "idm"=>1,
            ],
            [ 
                "idunitkerja"=>38,
            	"nama"=> 'Fitri Rachmawati',
                "nip"=>'197303202003122005'	,
                "jabatan"=>'Bendahara Pengeluaran',
                "rekening"=>'0011295444',
                "alamat"=>'Jl. Tanjungsari 116, Kec. Sukomanunggal',
                "idc"=>1,
                "idm"=>1,
            ],
            [ 
                "idunitkerja"=>52,
            	"nama"=> 'drg. Penni Rohma',
                "nip"=>'197903282006042020'	,
                "jabatan"=>'Bendahara Pengeluaran',
                "rekening"=>'1711001715',
                "alamat"=>'Jl. Kalibutuh No. 26, Kec. Bubutan',
                "idc"=>1,
                "idm"=>1,
            ],
            [ 
                "idunitkerja"=>72,
            	"nama"=> 'Irra Tjaturlita',
                "nip"=>'197411042010012001'	,
                "jabatan"=>'Bendahara Pengeluaran',
                "rekening"=>'1461002893',
                "alamat"=>'Jl. Rungkut Mejoyo Selatan IV/P-48, Kec. Tenggilis Mejoyo',
                "idc"=>1,
                "idm"=>1,
            ],
            [ 
                "idunitkerja"=>86,
            	"nama"=> 'Nuril Marliah, Amd. Analis Medis',
                "nip"=>'198208282005012008'	,
                "jabatan"=>'Bendahara Pengeluaran',
                "rekening"=>'1021004487',
                "alamat"=>'Jl. Raya Menganti Gg. Pasar No.20, Kec. Wiyung',
                "idc"=>1,
                "idm"=>1,
            ],
            [ 
                "idunitkerja"=>82,
            	"nama"=> 'drg Endang Sri Hartati',
                "nip"=>'196405281990012001'	,
                "jabatan"=>'Bendahara Pengeluaran',
                "rekening"=>'1861002906',
                "alamat"=>'Jl. Karang Rejo VI/4, Kec. Wonokromo',
                "idc"=>1,
                "idm"=>1,
            ],
            [ 
                "idunitkerja"=>59,
            	"nama"=> 'Alvah Setyaning Putri,A.Md Farm',
                "nip"=>'198408202008012006'	,
                "jabatan"=>'Bendahara Pengeluaran',
                "rekening"=>'0011295410',
                "alamat"=>'Jl. Wonokusumo Tengah 55, Kec. Semampir',
                "idc"=>1,
                "idm"=>1,
            ],

        ]);
    }
}
