<?php

use Illuminate\Database\Seeder;

class KPASeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \App\Pejabat::insert([
            [
                "idunitkerja"=>42,
                "nama"=>"dr. Diah Miryati",
                "nip"=>'198508212011012009',
                "jabatan"=>"KPA",
                "alamat"=>"Jl. Asem Raya 8, Kec. Asemrowo",
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>148,
                "nama"=>"dr. Tri Indah Rachmawati",
                "nip"=>'197203162006042017',
                "jabatan"=>"KPA",
                "alamat"=>"Jl. Raya Balas Klumprik, Kec. Wiyung",
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>41,
                "nama"=>"dr. Dewi Ayuning Asih",
                "nip"=>'197911282006042028',
                "jabatan"=>"KPA",
                "alamat"=>"Jl. Balongsari Tama No.1, Kec. Tandes",
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>103,
                "nama"=>"dr. Yessy Pebriaty Sukatandel",
                "nip"=>'197602292006042010',
                "jabatan"=>"KPA",
                "alamat"=>"Jl. Raya Bangkingan RT.02 RW.II, Kec. Lakarsantri",
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>79,
                "nama"=>"dr.Era Kartikawati",
                "nip"=>'197004302006042008',
                "jabatan"=>"KPA",
                "alamat"=>"Jl. Banyu Urip Kidul VI No. 8",
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>44,
                "nama"=>"Aloysius Tri Joehanto M.H",
                "nip"=>'197202142006041011',
                "jabatan"=>"KPA",
                "alamat"=>"Raya Benowo No. 47",
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>122,
                "nama"=>"drg. Elfi Asriningdiah Poedjiutami",
                "nip"=>'196508112003122001',
                "jabatan"=>"KPA",
                "alamat"=>"Jalan Dukuh Lebar, Gg Perintis Utama",
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>51,
                "nama"=>"dr. Murtiningrum",
                "nip"=>'197206212002122002',
                "jabatan"=>"KPA",
                "alamat"=>"Jl. Pandegiling No.223, DR. Soetomo, Tegalsari,",
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>85,
                "nama"=>"dr. Khusnul Khowatin",
                "nip"=>'198203262011012006',
                "jabatan"=>"KPA",
                "alamat"=>"Jl. Dukuh Kupang XXV No. 48",
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>61,
                "nama"=>"dr. Rr. Endang Dwihastutiningsih",
                "nip"=>'196709152002122001',
                "jabatan"=>"KPA",
                "alamat"=>"Gg. PoliklinikJl. Dupak Bangunrejo No. 6",
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>67,
                "nama"=>"dr. Thom's Danantosa",
                "nip"=>'197306022006041017',
                "jabatan"=>"KPA",
                "alamat"=>"Kapas Lor I F, Gading, Kec Tambaksari",
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>87,
                "nama"=>"drg. Harijanti Judaningsih",
                "nip"=>'196610051992032013',
                "jabatan"=>"KPA",
                "alamat"=>"Jl. Gayungsari Barat No. 124",
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>53,
                "nama"=>"dr. Tita Pusparini M.Kes",
                "nip"=>'198011202006042021',
                "jabatan"=>"KPA",
                "alamat"=>"Jl. Margodadi No. 36-38",
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>73,
                "nama"=>"drg. Ni Made Sariyani Dusak",
                "nip"=>'196401301989032007',
                "jabatan"=>"KPA",
                "alamat"=>"Jl. Gunung Anyar Lor No. 70",
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>81,
                "nama"=>"dr. Retno Widayanti",
                "nip"=>'196212201988022001',
                "jabatan"=>"KPA",
                "alamat"=>"Jl. Bendul Merisi No. 1, Jagir, Kec. Wonokromo",
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>88,
                "nama"=>"drg. Siti Januarsih",
                "nip"=>'195901011985122003',
                "jabatan"=>"KPA",
                "alamat"=>"Jl. Jemursari Sel. IV No. 5, Jemur wonosari, Kec. Wonocolo",
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>45,
                "nama"=>"dr. Ratih Sekar Ayu",
                "nip"=>'197508192005012009',
                "jabatan"=>"KPA",
                "alamat"=>"Jl. Raya Menganti No. 277A, Jeruk, Kec. Lakarsantri ",
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>138,
                "nama"=>"drg. Toetik Winarjati",
                "nip"=>'196202261993032002',
                "jabatan"=>"KPA",
                "alamat"=>"Jl. Kalijudan, Kalijudan, Kec. Mulyorejo",
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>70,
                "nama"=>"dr. Bernadetta Martini",
                "nip"=>'196106081988022001',
                "jabatan"=>"KPA",
                "alamat"=>"Rungkut Puskesmas No.1, Kali Rungkut, Kec. Rungkut",
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>90,
                "nama"=>"dr. Reyner Meilaksana Sumbung",
                "nip"=>'197905192006041018',
                "jabatan"=>"KPA",
                "alamat"=>"Kebonsari, Kec. Jambangan",
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>50,
                "nama"=>"drg. Dharmawati Zahara",
                "nip"=>'195707141981032006',
                "jabatan"=>"KPA",
                "alamat"=>"Jl. Kaliasin Pompa No.79-81, Kedungdoro, Kec. Tegalsari",
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>84,
                "nama"=>"dr. Ratnaika Wahdini",
                "nip"=>'196801042002122002',
                "jabatan"=>"KPA",
                "alamat"=>"Jalan Raya No.46, Kedurus, Kec. Karang Pilang",
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>62,
                "nama"=>"dr. Rosna Suswanti",
                "nip"=>'197705212011012008',
                "jabatan"=>"KPA",
                "alamat"=>"Jalan Tambak Deres No.2, Kenjeran, Kec. Bulak",
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>135,
                "nama"=>"drg. Dwiana Boediastika",
                "nip"=>'196203211989012002',
                "jabatan"=>"KPA",
                "alamat"=>"No 19 Sukolilo,Jl. Keputih Tegal, Keputih, Surabaya Timur",
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>49,
                "nama"=>"dr. Joyce Hestia Nugrahanti",
                "nip"=>'198404042014022002',
                "jabatan"=>"KPA",
                "alamat"=>"Jl. Jaksa Agung Suprapto No.10, Ketabang, Kec. Genteng",
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>60,
                "nama"=>"dr. Raden Muhammad Ali Satria",
                "nip"=>'198305212009031003',
                "jabatan"=>"KPA",
                "alamat"=>"Jl. Pesapen Selatan No.70, Krembangan Sel., Kec. Krembangan",
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>46,
                "nama"=>"dr. Heni Agustina",
                "nip"=>'197808242006042019',
                "jabatan"=>"KPA",
                "alamat"=>"Jl. Menganti Lidah Kulon No.5, Lidah Kulon, Kec. Lakarsantri",
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>47,
                "nama"=>"dr. Maulidina Fitria Ning Tiyas",
                "nip"=>'198611142014022002',
                "jabatan"=>"KPA",
                "alamat"=>"Jl. Raya Lontar No.26, Lontar, Kec. Sambikerep",
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>104,
                "nama"=>"drg. Endang Susilowati",
                "nip"=>'196508231994032003',
                "jabatan"=>"KPA",
                "alamat"=>"Jl. Raya Made No.116, Made, Kec. Sambikerep",
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>40,
                "nama"=>"dr. Winartuti Santoso M.Kes",
                "nip"=>'197509252006042013',
                "jabatan"=>"KPA",
                "alamat"=>"Jl. Manukan Dalam I/18, Kec. Tandes",
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>71,
                "nama"=>"dr. Dini Octavia Sitaresmi",
                "nip"=>'197510202007012020',
                "jabatan"=>"KPA",
                "alamat"=>"Jl. Medokan Asri Utara IV/31, Kec. Rungkut",
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>74,
                "nama"=>"dr. Medyana Puspita",
                "nip"=>'197501052007012017',
                "jabatan"=>"KPA",
                "alamat"=>"Jl. Manyar Rejo I/35, Kec. Sukolilo",
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>76,
                "nama"=>"dr. Riana Restuti",
                "nip"=>'196102181987122001',
                "jabatan"=>"KPA",
                "alamat"=>"Jl. Mulyorejo Utara 201 Blk, Kec. Mulyorejo",
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>83,
                "nama"=>"dr. Febria Sukmaini",
                "nip"=>'198002032010012008',
                "jabatan"=>"KPA",
                "alamat"=>"Jl. Ngagel Dadi III/17, Kec. Wonokromo",
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>66,
                "nama"=>"dr. Suluh Rahardjo",
                "nip"=>'196910212007011017',
                "jabatan"=>"KPA",
                "alamat"=>"Jl. Jolotundo Baru III/16, Kec. Tambaksari",
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>80,
                "nama"=>"drg. Puspa Karmila",
                "nip"=>'196412271990012001',
                "jabatan"=>"KPA",
                "alamat"=>"Jl. Makam Kembang Kuning No.6, Kec. Sawahan",
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>57,
                "nama"=>"dr. Evi Susanti",
                "nip"=>'196903032002122005',
                "jabatan"=>"KPA",
                "alamat"=>"Jl. Karang Tembok 39, Kec. Semampir",
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>56,
                "nama"=>"dr. Anggraini Dian Prameswari",
                "nip"=>'198404032009022012',
                "jabatan"=>"KPA",
                "alamat"=>"Jl. Jakarta No.9, Kec. Pabean Cantian",
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>68,
                "nama"=>"drg. Prasukma Yogawarti",
                "nip"=>'196504111990032005',
                "jabatan"=>"KPA",
                "alamat"=>"Jl. Pucang Anom Timur 72 Surabaya",
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>65,
                "nama"=>"dr. Dwiastuti Setyorini",
                "nip"=>'197807182006042017',
                "jabatan"=>"KPA",
                "alamat"=>"Jl. Rangkah VII/94, Kec. Tambaksari",
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>984,
                "nama"=>"dr. ERNA MINDARTI",
                "nip"=>'196702252003122001',
                "jabatan"=>"KPA",
                "alamat"=>"Jl. Sawah Pulo Lapangan No. 2",
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>77,
                "nama"=>"dr. Grace Augustien Worang",
                "nip"=>'195708091985032004',
                "jabatan"=>"KPA",
                "alamat"=>"Jl. Raya Arjuna 119, Kec. Sawahan",
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>43,
                "nama"=>"dr. Lolita Riamawati M.Kes",
                "nip"=>'196908262002122003',
                "jabatan"=>"KPA",
                "alamat"=>"Jl. Raya Kendung, Kec. Benowo",
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>89,
                "nama"=>"dr. Harjanti",
                "nip"=>'196802081993012001',
                "jabatan"=>"KPA",
                "alamat"=>"Jl. Sidosermo Gg. Damri No. 51, Kec. Wonocolo",
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>64,
                "nama"=>"dr. Basilius Agung Suryono",
                "nip"=>'197606142005011008',
                "jabatan"=>"KPA",
                "alamat"=>"Jl. Randu 102, Kec. Kenjeran",
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>55,
                "nama"=>"dr. Dwi Sapta Edy Purnama",
                "nip"=>'197611052007011009',
                "jabatan"=>"KPA",
                "alamat"=>"Jl. Simolawang II Barat No. 45 A, Kec. Simokerto",
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>39,
                "nama"=>"dr. Nurul Lailah M.Kes",
                "nip"=>'196811202000032003',
                "jabatan"=>"KPA",
                "alamat"=>"Jl. Gumuk Bogo VI/1, Kec. Sukomanunggal",
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>151,
                "nama"=>"dr. Sri Hawati",
                "nip"=>'196212141989032006',
                "jabatan"=>"KPA",
                "alamat"=>"Jl. Siwalankerto No. 134, Kec. Wonocolo",
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>121,
                "nama"=>"drg. Ilfin Martiana",
                "nip"=>'197003112006042004',
                "jabatan"=>"KPA",
                "alamat"=>"Jl. Tambak Wedi, Kec. Kenjeran",
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>54,
                "nama"=>"drg. Yekti Hapsari",
                "nip"=>'197910162007012009',
                "jabatan"=>"KPA",
                "alamat"=>"Jl. Ngaglik 87, Kec. Simokerto",
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>63,
                "nama"=>"drg. Isti Utami Hardjadinata",
                "nip"=>'196204301989012001',
                "jabatan"=>"KPA",
                "alamat"=>"Jl. Kedung Cowek 226, Kec. Kenjeran ",
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>38,
                "nama"=>"dr. Yunita Andriani",
                "nip"=>'197106262002122004',
                "jabatan"=>"KPA",
                "alamat"=>"Jl. Tanjungsari 116, Kec. Sukomanunggal",
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>52,
                "nama"=>"dr. Heri Siswanto",
                "nip"=>'196301262001121003',
                "jabatan"=>"KPA",
                "alamat"=>"Jl. Kalibutuh No. 26, Kec. Bubutan",
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>72,
                "nama"=>"dr. Dessy Jumiaty Setia",
                "nip"=>'196712081996032002',
                "jabatan"=>"KPA",
                "alamat"=>"Jl. Rungkut Mejoyo Selatan IV/P-48, Kec. Tenggilis Mejoyo",
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>86,
                "nama"=>"dr. Tatien Tjahjandari",
                "nip"=>'196011101987112001',
                "jabatan"=>"KPA",
                "alamat"=>"Jl. Raya Menganti Gg. Pasar No.20, Kec. Wiyung",
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>82,
                "nama"=>"drg. Dwiana Yuniarti",
                "nip"=>'197606022011012003',
                "jabatan"=>"KPA",
                "alamat"=>"Jl. Karang Rejo VI/4, Kec. Wonokromo",
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>59,
                "nama"=>"dr. Tienne Soeleman Caecilia Monica",
                "nip"=>'196105181987092001',
                "jabatan"=>"KPA",
                "alamat"=>"Jl. Wonokusumo Tengah 55, Kec. Semampir",
                "idc"=>1,
                "idm"=>1,
            ],

        ]);
    }
}
