<?php

use Illuminate\Database\Seeder;

class PPKSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \App\Pejabat::insert([
            [
                "idunitkerja" => 42,
                "nama"=>'Rifqi Agustiar Utomo',
                "nip"=>'197408252010011002',
                "jabatan"=>'PPK UPTD',
                "alamat"=>'Jl. Asem Raya 8, Kec. Asemrowo',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja" => 148,
                "nama"=>'Ramang Panu, A.M.K.L',
                "nip"=>'197011061993031005',
                "jabatan"=>'PPK UPTD',
                "alamat"=>'Jl. Raya Balas Klumprik, Kec. Wiyung',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja" => 41,
                "nama"=>'Mira Mardiana',
                "nip"=>'198203272011012007',
                "jabatan"=>'PPK UPTD',
                "alamat"=>'Jl. Balongsari Tama No.1, Kec. Tandes',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja" => 103,
                "nama"=>'Delly Lutifah',
                "nip"=>'197703282010012001',
                "jabatan"=>'PPK UPTD',
                "alamat"=>'Jl. Raya Bangkingan RT.02 RW.II, Kec. Lakarsantri',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja" => 79,
                "nama"=>'Sudarmoro, S.E',
                "nip"=>'197302112008011006',
                "jabatan"=>'PPK UPTD',
                "alamat"=>'Jl. Banyu Urip Kidul VI No. 8',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja" => 44,
                "nama"=>'Siti Nurfadilah',
                "nip"=>'198109182010012006',
                "jabatan"=>'PPK UPTD',
                "alamat"=>'Raya Benowo No. 47',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja" => 122,
                "nama"=>'Dini Agustinah, S.KM',
                "nip"=>'197008241995032003',
                "jabatan"=>'PPK UPTD',
                "alamat"=>'Jalan Dukuh Lebar, Gg Perintis Utama',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja" => 51,
                "nama"=>'Didi Isa Asmanu',
                "nip"=>'196405071985121002',
                "jabatan"=>'PPK UPTD',
                "alamat"=>'Jl. Pandegiling No.223, DR. Soetomo, Tegalsari,',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja" => 85,
                "nama"=>'Pipit Sri Purwati, SE',
                "nip"=>'196709261989032006',
                "jabatan"=>'PPK UPTD',
                "alamat"=>'Jl. Dukuh Kupang XXV No. 48',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja" => 61,
                "nama"=>'Estri Purwani',
                "nip"=>'196404071987032013',
                "jabatan"=>'PPK UPTD',
                "alamat"=>'Gg. PoliklinikJl. Dupak Bangunrejo No. 6',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja" => 67,
                "nama"=>'Soemarno',
                "nip"=>'197102021991031006',
                "jabatan"=>'PPK UPTD',
                "alamat"=>'Kapas Lor I F, Gading, Kec Tambaksari',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja" => 87,
                "nama"=>'Zainal Arifin',
                "nip"=>'196508141989031013',
                "jabatan"=>'PPK UPTD',
                "alamat"=>'Jl. Gayungsari Barat No. 124',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja" => 53,
                "nama"=>'Yudhi Arianto',
                "nip"=>'197809222010011002',
                "jabatan"=>'PPK UPTD',
                "alamat"=>'Jl. Margodadi No. 36-38',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja" => 73,
                "nama"=>'Khanim Inayati',
                "nip"=>'196405141985122003',
                "jabatan"=>'PPK UPTD',
                "alamat"=>'Jl. Gunung Anyar Lor No. 70',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja" => 81,
                "nama"=>'Fatimatuz Zahro A. Md',
                "nip"=>'198812302011012013',
                "jabatan"=>'PPK UPTD',
                "alamat"=>'Jl. Bendul Merisi No. 1, Jagir, Kec. Wonokromo',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja" => 88,
                "nama"=>'Mohamad Yasin, SH',
                "nip"=>'196807161991021001',
                "jabatan"=>'PPK UPTD',
                "alamat"=>'Jl. Jemursari Sel. IV No. 5, Jemur wonosari, Kec. Wonocolo',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja" => 45,
                "nama"=>'Fitri Indah Sari, A.Md Kep',
                "nip"=>'199403242020122002',
                "jabatan"=>'PPK UPTD',
                "alamat"=>'Jl. Raya Menganti No. 277A, Jeruk, Kec. Lakarsantri ',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja" => 138,
                "nama"=>'Arofah',
                "nip"=>'197603072009012001',
                "jabatan"=>'PPK UPTD',
                "alamat"=>'Jl. Kalijudan, Kalijudan, Kec. Mulyorejo',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja" => 70,
                "nama"=>'Ponari A.Md Kep',
                "nip"=>'198107082005011005',
                "jabatan"=>'PPK UPTD',
                "alamat"=>'Rungkut Puskesmas No.1, Kali Rungkut, Kec. Rungkut',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja" => 90,
                "nama"=>'Kusnan S.H',
                "nip"=>'196807201989031012',
                "jabatan"=>'PPK UPTD',
                "alamat"=>'Kebonsari, Kec. Jambangan',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja" => 50,
                "nama"=>'Yuni Rachmawati',
                "nip"=>'197706142010012002',
                "jabatan"=>'PPK UPTD',
                "alamat"=>'Jl. Kaliasin Pompa No.79-81, Kedungdoro, Kec. Tegalsari',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja" => 84,
                "nama"=>'Sri Lestari Ernawati',
                "nip"=>'196411101987032017',
                "jabatan"=>'PPK UPTD',
                "alamat"=>'Jalan Raya No.46, Kedurus, Kec. Karang Pilang',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja" => 62,
                "nama"=>'Chory Masitoh',
                "nip"=>'198211152006042012',
                "jabatan"=>'PPK UPTD',
                "alamat"=>'Jalan Tambak Deres No.2, Kenjeran, Kec. Bulak',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja" => 135,
                "nama"=>'Yanti Herdini, S.AP',
                "nip"=>'198003142010012001',
                "jabatan"=>'PPK UPTD',
                "alamat"=>'No 19 Sukolilo,Jl. Keputih Tegal, Keputih, Surabaya Timur',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja" => 49,
                "nama"=>'Wahyu Sasongko',
                "nip"=>'196712191994031003',
                "jabatan"=>'PPK UPTD',
                "alamat"=>'Jl. Jaksa Agung Suprapto No.10, Ketabang, Kec. Genteng',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja" => 75,
                "nama"=>'Suroiya In Junaidah, S.KM, M.Kes',
                "nip"=>'197501252006042018',
                "jabatan"=>'PPK UPTD',
                "alamat"=>'Jl. Arief Rahman Hakim No.99 B, Klampis Ngasem, Kec. Sukolilo',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja" => 60,
                "nama"=>'Palgunadi Soedjono, SH',
                "nip"=>'196412251987031013',
                "jabatan"=>'PPK UPTD',
                "alamat"=>'Jl. Pesapen Selatan No.70, Krembangan Sel., Kec. Krembangan',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja" => 46,
                "nama"=>'Meri Sibarani',
                "nip"=>'196503291984112001',
                "jabatan"=>'PPK UPTD',
                "alamat"=>'Jl. Menganti Lidah Kulon No.5, Lidah Kulon, Kec. Lakarsantri',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja" => 47,
                "nama"=>'Willy Achmad Agustian',
                "nip"=>'198308252005011003',
                "jabatan"=>'PPK UPTD',
                "alamat"=>'Jl. Raya Lontar No.26, Lontar, Kec. Sambikerep',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja" => 104,
                "nama"=>'drg.Sondang Ionetha Lumban',
                "nip"=>'197908312006042009',
                "jabatan"=>'PPK UPTD',
                "alamat"=>'Jl. Raya Made No.116, Made, Kec. Sambikerep',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja" => 40,
                "nama"=>'Yasroni, SE',
                "nip"=>'197006102008011020',
                "jabatan"=>'PPK UPTD',
                "alamat"=>'Jl. Manukan Dalam I/18, Kec. Tandes',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja" => 71,
                "nama"=>'Lenny Trisno Sugiarti, S.Ak',
                "nip"=>'197607082010012001',
                "jabatan"=>'PPK UPTD',
                "alamat"=>'Jl. Medokan Asri Utara IV/31, Kec. Rungkut',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja" => 74,
                "nama"=>'Titis Rachmanita',
                "nip"=>'198003282010012006',
                "jabatan"=>'PPK UPTD',
                "alamat"=>'Jl. Manyar Rejo I/35, Kec. Sukolilo',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja" => 69,
                "nama"=>'Dwi Retnaningsih',
                "nip"=>'196928122008012013',
                "jabatan"=>'PPK UPTD',
                "alamat"=>'Jl. Mojo Klanggru Wetan II/11, Kec. Gubeng',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja" => 117,
                "nama"=>'Eny Widyawati',
                "nip"=>'197111082006042009',
                "jabatan"=>'PPK UPTD',
                "alamat"=>'Jl. Tambak Asri XIII/17, Kec. Krembangan',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja" => 76,
                "nama"=>'Farida',
                "nip"=>'196511241987032005',
                "jabatan"=>'PPK UPTD',
                "alamat"=>'Jl. Mulyorejo Utara 201 Blk, Kec. Mulyorejo',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja" => 83,
                "nama"=>'Mutmainah., Amd. KL',
                "nip"=>'196404051987032014',
                "jabatan"=>'PPK UPTD',
                "alamat"=>'Jl. Ngagel Dadi III/17, Kec. Wonokromo',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja" => 66,
                "nama"=>'Sri Hastuti',
                "nip"=>'196410251986032015',
                "jabatan"=>'PPK UPTD',
                "alamat"=>'Jl. Jolotundo Baru III/16, Kec. Tambaksari',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja" => 80,
                "nama"=>'Eri Rahardian, SE',
                "nip"=>'198301232010012004',
                "jabatan"=>'PPK UPTD',
                "alamat"=>'Jl. Makam Kembang Kuning No.6, Kec. Sawahan',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja" => 57,
                "nama"=>'Budiono',
                "nip"=>'196503041990031009',
                "jabatan"=>'PPK UPTD',
                "alamat"=>'Jl. Karang Tembok 39, Kec. Semampir',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja" => 48,
                "nama"=>'Sylvia A. Md.KL',
                "nip"=>'196812061991032003',
                "jabatan"=>'PPK UPTD',
                "alamat"=>'Jl. Makam Peneleh 35, Kec. Genteng',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja" => 56,
                "nama"=>'Astutik',
                "nip"=>'196903271991012002',
                "jabatan"=>'PPK UPTD',
                "alamat"=>'Jl. Jakarta No.9, Kec. Pabean Cantian',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja" => 68,
                "nama"=>'Ira Yuly Sartikaningwati,S.AP',
                "nip"=>'197607092008012015',
                "jabatan"=>'PPK UPTD',
                "alamat"=>'Jl. Pucang Anom Timur 72 Surabaya',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja" => 78,
                "nama"=>'Rudi Novianto',
                "nip"=>'196911301989031003',
                "jabatan"=>'PPK UPTD',
                "alamat"=>'Jl. Kupang Gunung Raya No. 5 Surabaya',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja" => 65,
                "nama"=>'Novinda Nihayati',
                "nip"=>'198412142011012008',
                "jabatan"=>'PPK UPTD',
                "alamat"=>'Jl. Rangkah VII/94, Kec. Tambaksari',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja" => 77,
                "nama"=>'Cahyaning Darmastiti',
                "nip"=>'198210272006042012',
                "jabatan"=>'PPK UPTD',
                "alamat"=>'Jl. Raya Arjuna 119, Kec. Sawahan',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja" => 984,
                "nama"=>'Fonnyta Herfianti,S.KM',
                "nip"=>'197702172006042020',
                "jabatan"=>'PPK UPTD',
                "alamat"=>'Jl. Sawah Pulo Lapangan No. 2',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja" => 43,
                "nama"=>'Nur Aini',
                "nip"=>'197710122010012003',
                "jabatan"=>'PPK UPTD',
                "alamat"=>'Jl. Raya Kendung, Kec. Benowo',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja" => 89,
                "nama"=>'Desta BR Sinaga, Amd Kep',
                "nip"=>'197002101997032003',
                "jabatan"=>'PPK UPTD',
                "alamat"=>'Jl. Sidosermo Gg. Damri No. 51, Kec. Wonocolo',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja" => 58,
                "nama"=>'Suparwoto',
                "nip"=>'196609041989101001',
                "jabatan"=>'PPK UPTD',
                "alamat"=>'Jl. Sidodadi II',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja" => 64,
                "nama"=>'Mujiyah',
                "nip"=>'197609192007012011',
                "jabatan"=>'PPK UPTD',
                "alamat"=>'Jl. Randu 102, Kec. Kenjeran',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja" => 55,
                "nama"=>'Tri Sulistyaning Ati',
                "nip"=>'197511112008012010',
                "jabatan"=>'PPK UPTD',
                "alamat"=>'Jl. Simolawang II Barat No. 45 A, Kec. Simokerto',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja" => 39,
                "nama"=>'Hindana Fari Oktavia Faridatur Rosidah',
                "nip"=>'198710032014022001',
                "jabatan"=>'PPK UPTD',
                "alamat"=>'Jl. Gumuk Bogo VI/1, Kec. Sukomanunggal',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja" => 151,
                "nama"=>'Khoirul Amin',
                "nip"=>'196608181988111001',
                "jabatan"=>'PPK UPTD',
                "alamat"=>'Jl. Siwalankerto No. 134, Kec. Wonocolo',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja" => 121,
                "nama"=>'Mahardianto Kurniawan',
                "nip"=>'196809081990031004',
                "jabatan"=>'PPK UPTD',
                "alamat"=>'Jl. Tambak Wedi, Kec. Kenjeran',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja" => 54,
                "nama"=>'Sri Sundari',
                "nip"=>'197306032010012001',
                "jabatan"=>'PPK UPTD',
                "alamat"=>'Jl. Ngaglik 87, Kec. Simokerto',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja" => 63,
                "nama"=>'Debby Dwijayanti S.KM',
                "nip"=>'198211082010012009',
                "jabatan"=>'PPK UPTD',
                "alamat"=>'Jl. Kedung Cowek 226, Kec. Kenjeran ',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja" => 38,
                "nama"=>'Meita Dwi Setyarini',
                "nip"=>'198205052006042032',
                "jabatan"=>'PPK UPTD',
                "alamat"=>'Jl. Tanjungsari 116, Kec. Sukomanunggal',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja" => 52,
                "nama"=>'Soeharijati',
                "nip"=>'196705111988012001',
                "jabatan"=>'PPK UPTD',
                "alamat"=>'Jl. Kalibutuh No. 26, Kec. Bubutan',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja" => 72,
                "nama"=>'Maria Ulfah',
                "nip"=>'198512232010012005',
                "jabatan"=>'PPK UPTD',
                "alamat"=>'Jl. Rungkut Mejoyo Selatan IV/P-48, Kec. Tenggilis Mejoyo',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja" => 86,
                "nama"=>'Nor Endah Rahmawati, S.KM',
                "nip"=>'198605172010012011',
                "jabatan"=>'PPK UPTD',
                "alamat"=>'Jl. Raya Menganti Gg. Pasar No.20, Kec. Wiyung',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja" => 82,
                "nama"=>'Asikin',
                "nip"=>'196808061990081001',
                "jabatan"=>'PPK UPTD',
                "alamat"=>'Jl. Karang Rejo VI/4, Kec. Wonokromo',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja" => 59,
                "nama"=>'Lies Etika',
                "nip"=>'196503261986032006',
                "jabatan"=>'PPK UPTD',
                "alamat"=>'Jl. Wonokusumo Tengah 55, Kec. Semampir',
                "idc"=>1,
                "idm"=>1,
            ],
        ]);
    }
}
