<?php

use Illuminate\Database\Seeder;

class PPTKSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \App\Pejabat::insert([
            [
                "idunitkerja"=>42,
                "nama"=>"Suci Wahyuning Ati",
                "nip"=>"198406272006042017",
                "jabatan"=>"PPTK",
                "alamat"=>'Jl. Asem Raya 8, Kec. Asemrowo',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>148,
                "nama"=>"drg. Fitri Wulandari",
                "nip"=>"197601162014122001",
                "jabatan"=>"PPTK",
                "alamat"=>'Jl. Raya Balas Klumprik, Kec. Wiyung',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>41,
                "nama"=>"Dewi Mas'uddah",
                "nip"=>"198305032010012012",
                "jabatan"=>"PPTK",
                "alamat"=>'Jl. Balongsari Tama No.1, Kec. Tandes',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>103,
                "nama"=>"DESY ARIANI, A.Md.Kep",
                "nip"=>"198812042011012010",
                "jabatan"=>"PPTK",
                "alamat"=>'Jl. Raya Bangkingan RT.02 RW.II, Kec. Lakarsantri',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>79,
                "nama"=>"Diah Anis Irawati, Amd.Keb",
                "nip"=>"197901082006042018",
                "jabatan"=>"PPTK",
                "alamat"=>'Jl. Banyu Urip Kidul VI No. 8',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>44,
                "nama"=>"dr. Jazimatul Mahsunah",
                "nip"=>"198503092020122001",
                "jabatan"=>"PPTK",
                "alamat"=>'Raya Benowo No. 47',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>122,
                "nama"=>"dr. Susan Dani Suryono",
                "nip"=>"197710272006042017",
                "jabatan"=>"PPTK",
                "alamat"=>'Jalan Dukuh Lebar, Gg Perintis Utama',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>51,
                "nama"=>"dr. Aulia Suprihatin",
                "nip"=>"198508072020122002",
                "jabatan"=>"PPTK",
                "alamat"=>'Jl. Pandegiling No.223, DR. Soetomo, Tegalsari,',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>85,
                "nama"=>"dr. Hikmatul Maghfiroh",
                "nip"=>"199004112019022001",
                "jabatan"=>"PPTK",
                "alamat"=>'Jl. Dukuh Kupang XXV No. 48',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>61,
                "nama"=>"IKE SULISTYO WIJAYATI AS, SST",
                "nip"=>"198001222008012010",
                "jabatan"=>"PPTK",
                "alamat"=>'Gg. PoliklinikJl. Dupak Bangunrejo No. 6',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>67,
                "nama"=>"dr. Wenny Lestari",
                "nip"=>"198806122020122004",
                "jabatan"=>"PPTK",
                "alamat"=>'Kapas Lor I F, Gading, Kec Tambaksari',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>87,
                "nama"=>"dr. Ike Nuralinda Megasari",
                "nip"=>"198805022014022001",
                "jabatan"=>"PPTK",
                "alamat"=>'Jl. Gayungsari Barat No. 124',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>53,
                "nama"=>"drg. Tri Peni Laksanawati",
                "nip"=>"197503062006042024",
                "jabatan"=>"PPTK",
                "alamat"=>'Jl. Margodadi No. 36-38',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>73,
                "nama"=>"dr. Nina Apriyanti, M.Kes",
                "nip"=>"197610052006042025",
                "jabatan"=>"PPTK",
                "alamat"=>'Jl. Gunung Anyar Lor No. 70',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>81,
                "nama"=>"dr. Ria Fikdawati",
                "nip"=>"199104242020122001",
                "jabatan"=>"PPTK",
                "alamat"=>'Jl. Bendul Merisi No. 1, Jagir, Kec. Wonokromo',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>88,
                "nama"=>"dr. Dyah Fitriningrum, M. Imun",
                "nip"=>"197509192005022008",
                "jabatan"=>"PPTK",
                "alamat"=>'Jl. Jemursari Sel. IV No. 5, Jemur wonosari, Kec. Wonocolo',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>45,
                "nama"=>"Uswatun Khasanah",
                "nip"=>"198205072008012008",
                "jabatan"=>"PPTK",
                "alamat"=>'Jl. Raya Menganti No. 277A, Jeruk, Kec. Lakarsantri ',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>138,
                "nama"=>"Linda Widyastuti",
                "nip"=>"198509052009042003",
                "jabatan"=>"PPTK",
                "alamat"=>'Jl. Kalijudan, Kalijudan, Kec. Mulyorejo',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>70,
                "nama"=>"Heni, A.md Kep",
                "nip"=>"198401162010012006",
                "jabatan"=>"PPTK",
                "alamat"=>'Rungkut Puskesmas No.1, Kali Rungkut, Kec. Rungkut',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>90,
                "nama"=>"dr.Puspita Sari",
                "nip"=>"197007102006042018",
                "jabatan"=>"PPTK",
                "alamat"=>'Kebonsari, Kec. Jambangan',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>50,
                "nama"=>"dr. AM. Dayanti Dadiningrum",
                "nip"=>"196407102002122002",
                "jabatan"=>"PPTK",
                "alamat"=>'Jl. Kaliasin Pompa No.79-81, Kedungdoro, Kec. Tegalsari',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>84,
                "nama"=>"dr. Gerryd Dina S",
                "nip"=>"197301222014122002",
                "jabatan"=>"PPTK",
                "alamat"=>'Jalan Raya No.46, Kedurus, Kec. Karang Pilang',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>62,
                "nama"=>"Linda Rakhmania",
                "nip"=>"198103232006042046",
                "jabatan"=>"PPTK",
                "alamat"=>'Jalan Tambak Deres No.2, Kenjeran, Kec. Bulak',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>135,
                "nama"=>"dr. Rahmi Hilaliyah",
                "nip"=>"198103232006042046",
                "jabatan"=>"PPTK",
                "alamat"=>'No 19 Sukolilo,Jl. Keputih Tegal, Keputih, Surabaya Timur',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>49,
                "nama"=>"dr. Denti Lina Rouli Boru T",
                "nip"=>"198404042014022002",
                "jabatan"=>"PPTK",
                "alamat"=>'Jl. Jaksa Agung Suprapto No.10, Ketabang, Kec. Genteng',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>75,
                "nama"=>"dr. Evi Retno Wulandari",
                "nip"=>"197603222010012002",
                "jabatan"=>"PPTK",
                "alamat"=>'Jl. Arief Rahman Hakim No.99 B, Klampis Ngasem, Kec. Sukolilo',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>60,
                "nama"=>"dr. Winto Setiyo Utomo",
                "nip"=>"198309242010011005",
                "jabatan"=>"PPTK",
                "alamat"=>'Jl. Pesapen Selatan No.70, Krembangan Sel., Kec. Krembangan',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>46,
                "nama"=>"dr.Aning Dyah Wijayanti",
                "nip"=>"197907282011012007",
                "jabatan"=>"PPTK",
                "alamat"=>'Jl. Menganti Lidah Kulon No.5, Lidah Kulon, Kec. Lakarsantri',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>47,
                "nama"=>"dr. Frida Afiana",
                "nip"=>"198005102006042026",
                "jabatan"=>"PPTK",
                "alamat"=>'Jl. Raya Lontar No.26, Lontar, Kec. Sambikerep',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>104,
                "nama"=>"dr.Shinta Besly Cumlaude",
                "nip"=>"199002172020122002",
                "jabatan"=>"PPTK",
                "alamat"=>'Jl. Raya Lontar No.26, Lontar, Kec. Sambikerep',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>40,
                "nama"=>"dr Listiawati Pitna",
                "nip"=>"198507302011012008",
                "jabatan"=>"PPTK",
                "alamat"=>'Jl. Manukan Dalam I/18, Kec. Tandes',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>71,
                "nama"=>"Agustin Indriyani S. ST",
                "nip"=>"197408112005012007",
                "jabatan"=>"PPTK",
                "alamat"=>'Jl. Medokan Asri Utara IV/31, Kec. Rungkut',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>74,
                "nama"=>"dr. Farmitalia Nisa Tristianti",
                "nip"=>"199406062020122002",
                "jabatan"=>"PPTK",
                "alamat"=>'Jl. Manyar Rejo I/35, Kec. Sukolilo',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>69,
                "nama"=>"Ani Prihandini AMd. Keb",
                "nip"=>"197212151991032003",
                "jabatan"=>"PPTK",
                "alamat"=>'Jl. Mojo Klanggru Wetan II/11, Kec. Gubeng',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>117,
                "nama"=>"dr. Farida Cristanti",
                "nip"=>"198722082020122002",
                "jabatan"=>"PPTK",
                "alamat"=>'Jl. Tambak Asri XIII/17, Kec. Krembangan',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>76,
                "nama"=>"dr. Eko Apriyanto",
                "nip"=>"197904112005011017",
                "jabatan"=>"PPTK",
                "alamat"=>'Jl. Mulyorejo Utara 201 Blk, Kec. Mulyorejo',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>83,
                "nama"=>"dr. Nina Pratiwi",
                "nip"=>"198601302020122002",
                "jabatan"=>"PPTK",
                "alamat"=>'Jl. Ngagel Dadi III/17, Kec. Wonokromo',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>66,
                "nama"=>"dr. Winda Winastuti",
                "nip"=>"198110122014022002",
                "jabatan"=>"PPTK",
                "alamat"=>'Jl. Jolotundo Baru III/16, Kec. Tambaksari',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>80,
                "nama"=>"Ully Sriwardani, Amd Analis Kes",
                "nip"=>"198106062005012018",
                "jabatan"=>"PPTK",
                "alamat"=>'Jl. Makam Kembang Kuning No.6, Kec. Sawahan',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>57,
                "nama"=>"dr Lutfi Wijayanto",
                "nip"=>"198307262009021003",
                "jabatan"=>"PPTK",
                "alamat"=>'Jl. Karang Tembok 39, Kec. Semampir',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>48,
                "nama"=>"Aan Nurdiyanto, S.Kep.Ns",
                "nip"=>"197911052010011010",
                "jabatan"=>"PPTK",
                "alamat"=>'Jl. Makam Peneleh 35, Kec. Genteng',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>56,
                "nama"=>"dr. Wahyu Hutomo",
                "nip"=>"198904012020121002",
                "jabatan"=>"PPTK",
                "alamat"=>'Jl. Jakarta No.9, Kec. Pabean Cantian',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>68,
                "nama"=>"dr. Dini Nur Aini",
                "nip"=>"199010282020122004",
                "jabatan"=>"PPTK",
                "alamat"=>'Jl. Pucang Anom Timur 72 Surabaya',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>78,
                "nama"=>"Probosiwi, Amd Kep",
                "nip"=>"199202062020122001",
                "jabatan"=>"PPTK",
                "alamat"=>'Jl. Kupang Gunung Raya No. 5 Surabaya',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>65,
                "nama"=>"drg. Esti Sriwuri",
                "nip"=>"196012171987032008",
                "jabatan"=>"PPTK",
                "alamat"=>'Jl. Rangkah VII/94, Kec. Tambaksari',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>984,
                "nama"=>"Ika Maulidia Nugraheni",
                "nip"=>"199009092019022003",
                "jabatan"=>"PPTK",
                "alamat"=>'Jl. Sawah Pulo Lapangan No. 2',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>77,
                "nama"=>"Alfin Nadiroh Amd.Keb",
                "nip"=>"198008092006042023",
                "jabatan"=>"PPTK",
                "alamat"=>'Jl. Raya Arjuna 119, Kec. Sawahan',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>43,
                "nama"=>"dr. Nurul Ihsani",
                "nip"=>"198808312014022001",
                "jabatan"=>"PPTK",
                "alamat"=>'Jl. Raya Kendung, Kec. Benowo',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>89,
                "nama"=>"dr. Kusuma Wardana",
                "nip"=>"198606082019021002",
                "jabatan"=>"PPTK",
                "alamat"=>'Jl. Sidosermo Gg. Damri No. 51, Kec. Wonocolo',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>58,
                "nama"=>"Nurul Huda, AMd.Keb, S.Sos",
                "nip"=>"196809071990032010",
                "jabatan"=>"PPTK",
                "alamat"=>'Jl. Sidodadi II',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>58,
                "nama"=>"dr. Dwi Tyasanti Jiwangga Putri",
                "nip"=>"198410172019022001",
                "jabatan"=>"PPTK",
                "alamat"=>'Jl. Sidodadi II',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>64,
                "nama"=>"drg. Elyana Retno Ningrum",
                "nip"=>"197912282006042015",
                "jabatan"=>"PPTK",
                "alamat"=>'Jl. Randu 102, Kec. Kenjeran',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>55,
                "nama"=>"dr. Dania Rahmawati",
                "nip"=>"198502272011012009",
                "jabatan"=>"PPTK",
                "alamat"=>'Jl. Simolawang II Barat No. 45 A, Kec. Simokerto',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>151,
                "nama"=>"ERMA TRI WAHYUNI, A.Md.Keb",
                "nip"=>"198503102009032011",
                "jabatan"=>"PPTK",
                "alamat"=>'Jl. Siwalankerto No. 134, Kec. Wonocolo',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>121,
                "nama"=>"drg. Erlysa Asmara",
                "nip"=>"198003162014032001",
                "jabatan"=>"PPTK",
                "alamat"=>'Jl. Tambak Wedi, Kec. Kenjeran',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>54,
                "nama"=>"Purdijanti Listijorini",
                "nip"=>"197010272007012010",
                "jabatan"=>"PPTK",
                "alamat"=>'Jl. Ngaglik 87, Kec. Simokerto',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>63,
                "nama"=>"Novi Arianti",
                "nip"=>"197905282007012008",
                "jabatan"=>"PPTK",
                "alamat"=>'Jl. Kedung Cowek 226, Kec. Kenjeran ',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>38,
                "nama"=>"Nirmala Novianti",
                "nip"=>"199611032019022002",
                "jabatan"=>"PPTK",
                "alamat"=>'Jl. Tanjungsari 116, Kec. Sukomanunggal',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>52,
                "nama"=>"Totok Yulianto",
                "nip"=>"197307182006041011",
                "jabatan"=>"PPTK",
                "alamat"=>'Jl. Kalibutuh No. 26, Kec. Bubutan',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>72,
                "nama"=>"EKO AGUS PRIONO, A.Md. Kep",
                "nip"=>"198408032019021002",
                "jabatan"=>"PPTK",
                "alamat"=>'Jl. Rungkut Mejoyo Selatan IV/P-48, Kec. Tenggilis Mejoyo',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>86,
                "nama"=>"dr. Novia Komalasari",
                "nip"=>"198104262009022006",
                "jabatan"=>"PPTK",
                "alamat"=>'Jl. Raya Menganti Gg. Pasar No.20, Kec. Wiyung',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>82,
                "nama"=>"Ely Sariani,S.ST",
                "nip"=>"197002261991032006",
                "jabatan"=>"PPTK",
                "alamat"=>'Jl. Karang Rejo VI/4, Kec. Wonokromo',
                "idc"=>1,
                "idm"=>1,
            ],
            [
                "idunitkerja"=>59,
                "nama"=>"Roro Rahayu,Amd Kep",
                "nip"=>"198710042010012007",
                "jabatan"=>"PPTK",
                "alamat"=>'Jl. Wonokusumo Tengah 55, Kec. Semampir',
                "idc"=>1,
                "idm"=>1,
            ],

        ]);
    }
}
